CI: Enforce specific target branch for PRs

diff --git a/.github/workflows/static_checks.yml b/.github/workflows/static_checks.yml
--- a/.github/workflows/static_checks.yml
+++ b/.github/workflows/static_checks.yml
@@ -10,6 +10,9 @@ on:
         value: ${{ jobs.static-checks.outputs.sources-changed }}
   workflow_dispatch:
 
+env:
+  TARGET_BRANCH: ${{ vars.TARGET_BRANCH || github.event.repository.default_branch }}
+
 jobs:
   static-checks:
     name: Code style, file formatting, and docs
@@ -19,6 +22,12 @@ jobs:
       changed-files: '"${{ steps.changed-files.outputs.clangd_all_changed_files }}"' # Wrap with quotes to bookend internal quote separators.
       sources-changed: ${{ steps.changed-files.outputs.sources_any_changed }}
     steps:
+      - name: Ensure correct target
+        if: github.event_name == 'pull_request' && github.head_ref != env.TARGET_BRANCH
+        run: |
+          echo "::error::Branch should target '${{ env.TARGET_BRANCH }}'"
+          exit 1
+
       - name: Checkout
         uses: actions/checkout@v6
         with:
